# Generated by Django 3.1.3 on 2020-11-24 15:56

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20201124_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='slug',
            field=autoslug.fields.AutoSlugField(unique=True),
        ),
    ]
